#!/bin/bash
# Lightweight script to set up AMM7 on CIRRUS
 
display_usage() { 
   echo
   echo "  Auto-Config: AMM7 on CIRRUS"
   echo "  ***************************************"
   echo
   echo "  usage: ${0##*/} -w path_to_install_nemo -x path_to_intall_xios -s path_to_repo"
   echo
   echo "  flags:  -w full path to where nemo will be installed"
   echo "          -x full path to where xios will be installed"
   echo "          -s full path to where AMM7 repository resides"
   echo
   exit 1
	} 
# if less than three arguments supplied, display usage 
	if [  $# -le 5 ] 
	then 
		display_usage
		exit 1
	fi 
# if less than two arguments supplied, display usage 
	if [  $# -ge 7 ] 
	then 
		display_usage
		exit 1
	fi 
# check whether user had supplied -h or --help . If yes display usage 
	if [[ ( $# == "--help") ||  $# == "-h" ]] 
	then 
		display_usage
		exit 0
	fi 

while getopts w:x:s: option
  do
  case "${option}"
  in
  w) export WORK_DIR=${OPTARG};;
  x) export XIOS_DIR=${OPTARG};;
  s) export REPO_DIR=${OPTARG};;
  esac
done

if [ ${WORK_DIR:0:1} != "/" ]; then
  echo "WORK_DIR must use full path"
  exit 1
fi

if [ ${XIOS_DIR:0:1} != "/" ]; then
  echo "XIOS_DIR must use full path"
  exit 1
fi

if [ ${REPO_DIR:0:1} != "/" ]; then
  echo "REPO_DIR must use full path"
  exit 1
fi

# Change to some working directory of choice
if [ ! -d "$WORK_DIR" ]; then
  mkdir $WORK_DIR
fi
cd $WORK_DIR

echo "Making sure that the correct modules are loaded"

module purge
module load intel-compilers-18/18.05.274 netcdf-parallel/4.6.2-intel18-impi18 
export HDF5_DIR='/lustre/sw/hdf5parallel/1.10.4-intel18-impi18'

# Checkout the NEMO code from the SVN Paris repository 
echo "Checking out NEMO repository"
svn co http://forge.ipsl.jussieu.fr/nemo/svn/NEMO/releases/release-4.0.1 --depth empty nemo
svn co http://forge.ipsl.jussieu.fr/nemo/svn/NEMO/releases/release-4.0.1/src --depth infinity nemo/src
svn co http://forge.ipsl.jussieu.fr/nemo/svn/utils/build/mk nemo/mk
svn co http://forge.ipsl.jussieu.fr/nemo/svn/NEMO/releases/release-4.0.1/cfgs/SHARED nemo/cfgs/SHARED
svn export http://forge.ipsl.jussieu.fr/nemo/svn/NEMO/releases/release-4.0.1/cfgs/ref_cfgs.txt nemo/cfgs/ref_cfgs.txt
svn co http://forge.ipsl.jussieu.fr/nemo/svn/vendors/FCM nemo/ext/FCM
svn co http://forge.ipsl.jussieu.fr/nemo/svn/vendors/IOIPSL nemo/ext/IOIPSL
svn export http://forge.ipsl.jussieu.fr/nemo/svn/utils/build/makenemo nemo/makenemo
mkdir nemo/arch

# Setup the directory structure for the ENSEMBLE
mkdir $WORK_DIR/nemo/cfgs/AMM7
# Define the location of where the AMM7 forcing files are to be downloaded 
export DOWNLOAD_DIR="$WORK_DIR/nemo/cfgs/AMM7/EXP00/"

echo $XIOS_DIR
# Choose an appropriate directory for your XIOS installation
if [ ! -d "$XIOS_DIR" ]; then
  mkdir $XIOS_DIR
fi
cd $XIOS_DIR
echo $PWD
echo "Checking out xios repository"
svn co http://forge.ipsl.jussieu.fr/ioserver/svn/XIOS/branchs/xios-2.5@1627 xios
cd xios
cp $REPO_DIR/arch/xios/* ./arch
echo "Compiling xios"
./make_xios --full --prod --arch cirrus --netcdf_lib netcdf4_par --job 4

# Let's update the path to xios
export XIOS_DIR=$XIOS_DIR/xios

cd $WORK_DIR/nemo
cp $REPO_DIR/arch/nemo/* ./arch

echo 'AMM7 OCE' >> $WORK_DIR/nemo/cfgs/work_cfgs.txt

mkdir cfgs/AMM7/EXP00
echo "Gathering forcing data"

export CONFIG_DIR=$WORK_DIR/nemo/cfgs/AMM7

mkdir $CONFIG_DIR/ENSEMBLE_MEMBERS
n=`cat $REPO_DIR/scripts/model_list | wc -l`
# Set each ENSEMBLE MEMBER directory up
for i in  $(seq 1 $n); do
  model=`sed -n $i,$i\p $REPO_DIR/scripts/model_list`
  cd $CONFIG_DIR/ENSEMBLE_MEMBERS
  mkdir $model
  cd $model
  ln -s ../../EXP00/xios_server.exe xios_server.exe
  ln -s ../../EXP00/opa nemo
  ln -s ../../../SHARED/namelist_ref namelist_ref
  ln -s ../../../SHARED/grid_def_nemo.xml grid_def_nemo.xml
  ln -s ../../../SHARED/field_def_nemo-oce.xml field_def_nemo-oce.xml
  ln -s ../../../SHARED/domain_def_nemo.xml domain_def_nemo.xml
  ln -s ../../ENSEMBLE_INPUTS/iodef.xml iodef.xml
  ln -s ../../ENSEMBLE_INPUTS/file_def.xml file_def.xml
  ln -s ../../ENSEMBLE_INPUTS/context_nemo.xml context_nemo.xml
  ln -s ../../ENSEMBLE_INPUTS/coordinates.skagbdy.nc coordinates.skagbdy.nc
  ln -s ../../ENSEMBLE_INPUTS/coordinates.bdy.nc coordinates.bdy.nc
  ln -s ../../ENSEMBLE_INPUTS/DOM/$model\_domain_cfg.nc domain_cfg.nc
  ln -s ../../ENSEMBLE_INPUTS/TIDE TIDE
  ln -s ../../ENSEMBLE_INPUTS/RIV RIV
  ln -s ../../ENSEMBLE_INPUTS/kd490.nc kd490.nc
  ln -s ../../ENSEMBLE_INPUTS/chlorophyll.nc chlorophyll.nc
  ln -s ../../ENSEMBLE_INPUTS/BDY_SKAG BDY_SKAG
  ln -s ../../ENSEMBLE_INPUTS/BDY BDY
  ln -s ../../ENSEMBLE_INPUTS/ATM ATM
  ln -s ../../ENSEMBLE_INPUTS/IC/inits_m01.nc inits_m01.nc
  mkdir meta_out
  mkdir RESTARTS
  mkdir OUTPUTS
done

mkdir $CONFIG_DIR/ENSEMBLE_INPUTS
mkdir $CONFIG_DIR/ENSEMBLE_INPUTS/RIV
mkdir $CONFIG_DIR/ENSEMBLE_INPUTS/TIDE
mkdir $CONFIG_DIR/ENSEMBLE_INPUTS/IC
mkdir $CONFIG_DIR/ENSEMBLE_INPUTS/BDY
mkdir $CONFIG_DIR/ENSEMBLE_INPUTS/BDY_SKAG
mkdir $CONFIG_DIR/ENSEMBLE_INPUTS/DOM
mkdir $CONFIG_DIR/ENSEMBLE_INPUTS/ATM

ln -s $XIOS_DIR/bin/xios_server.exe $CONFIG_DIR/EXP00/xios_server.exe

cp $REPO_DIR/EXP00/* $CONFIG_DIR/EXP00/
cp -r $REPO_DIR/MY_SRC $CONFIG_DIR
cp $REPO_DIR/cpp_AMM7.fcm $CONFIG_DIR/

cd $WORK_DIR/nemo

echo "Compiling nemo AMM7 Config"
./makenemo -m cirrus -r AMM7 -j 8

echo
echo "  Auto-Config: AMM7"
echo "  *****************************"
echo
echo "  To run the AMM7 Configuration:"
echo
echo "  - update the runscript.pbs accordingly "
echo "      (project code, nodes, modules, etc)"
echo
echo "  - submit via the qsub command"
echo    
